
const work = [
    {name: 'Coderhouse',
    title: 'React JS Teacher',
    description:'August 2020 - Present',
    content: ['Taught and Assisted students with web development concepts',
              'Help the students build an e-commerce app from scratch',
              'React.js Development',
            'HTML, CSS, Javascript, Node, CLI, NPM, GIT version control, project management',
            ,
            ]
    },
    {name: 'Lyrtron S.A',
    content: ['Developed Stress and Worst Case Circuit Analysis (SWCCA) in power inverters',
                'SWCCA for Power Optimizers' ,
                'Used gallium nitride (eGaN) and Silicon Carbide (SiC) transistors' ,
                'Worked for clients such as Advanced Energy (USA) and AMPT (USA)'
            ],
    title: 'Power Electronics Engineer',
    description:'September 2018 - April 2019',
    },
    {name: 'ICyTE',
    content: ['Won a national scholarship to do research in Compressed Sensing and Systems on Chip',
              'Developed a Compressed Sensing System in a Xilinx ZYNQ SoC (Zedboard)',
            'Designed and Built a Delta/Sigma Digital-to-Analog converter'],
    title: 'Embedded Systems Engineer',
    description:'October 2016 - March 2018',
    },
    {name: 'INVAP S.E',
    content: ['Developed a Printed Circuit Board for an aerospacial system',
              'Used Microsemi FPGA Pro ASIC3 (CCGA)',
              'Studied of the CCGA technology, footprint, and solder requirements',
              'Design of circuit layout in Altium Designer',
],
    title: 'Avionics Engineer (Internship)',
    description:'January 2016 - March 2016',
    },
    {name: 'UNMDP',
    content: ['C/C++','React.js','VHDL', 'RTOS','Xilinx/HLS'],
    title: 'Professor in Experimental Physics',
    description:'November 2014 – November 2017',
    },
]

export default work;

