
const work = [
    {name: 'Coderhouse',
    title: 'React JS Teacher',
    description:'2020 - Present',
    content: ['Taught and Assisted students with web development concepts.',
              'Help the students build an e-commerce app from scratch.',
            'HTML, CSS, Javascript, React JS, Node, CLI, NPM, Firebase, GIT version control, project management.',
            ,
            ]
    },
    {name: 'Lyrtron S.A',
    content: ['Developed Stress and Worst Case Circuit Analysis (SWCCA) in Power Inverters and Power Optimizers.',
                'Used gallium nitride (eGaN) and Silicon Carbide (SiC) transistors.' ,
                'Worked for clients such as Advanced Energy (USA) and AMPT (USA).'
            ],
    title: 'Power Electronics Engineer',
    description:'2018 - 2019',
    },
    {name: 'ICyTE',
    content: ['Developed a Compressed Sensing System in a Xilinx ZYNQ 7000 SoC.',
              'Coded in C/C++, VHDL and Xilinx HLS.',
              'Created a Graphic Interface in Python with Network Capabilities',
            'Designed and Built a Delta/Sigma Digital-to-Analog converter.'],
    title: 'Embedded Systems Engineer',
    description:'2016 - 2018',
    },
    {name: 'INVAP S.E',
    content: ['Developed a Printed Circuit Board for an aerospacial system',
              'Used Microsemi FPGA Pro ASIC3 (CCGA)',
              'Studied of the CCGA technology, footprint, and solder requirements',
              'Design of circuit layout in Altium Designer',
],
    title: 'Avionics Engineer (Internship)',
    description:'2016 - 2016',
    },
    {name: 'UNMDP',
    content: ['Regular status obtained by contest','Taught and graded Laboratory assignments.','Designed Experiments.'],
    title: 'Professor Assistanship in Experimental Physics',
    description:'2014 – 2017',
    },
]

export default work;

